trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - powershell: |
      $env:JAVA_HOME = "C:\Program Files\Eclipse Adoptium\jdk-17.0.19.10-hotspot"
      $env:MAVEN_HOME = "C:\Users\USER\tools\apache-maven-3.9.16"
      $env:Path = "$env:JAVA_HOME\bin;$env:MAVEN_HOME\bin;$env:Path"

      java -version
      mvn -version
      mvn clean test
    displayName: Compilar y ejecutar pruebas JUnit

  - task: PublishTestResults@2
    displayName: Publicar resultados JUnit
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      failTaskOnFailedTests: true
