trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: JavaToolInstaller@0
    displayName: Usar Java 17
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled

  - task: Maven@4
    displayName: Compilar y ejecutar pruebas automatizadas
    inputs:
      mavenPomFile: pom.xml
      goals: clean test
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: JDKVersion
      jdkVersionOption: '1.17'
      mavenVersionOption: Default
      mavenOptions: '-Xmx1024m'

  - task: PublishTestResults@2
    displayName: Publicar resultados JUnit
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      failTaskOnFailedTests: true
